spring:
  sql:
    init:
      mode: always   # v2.5 ?? ?? sql.init.mode? ????? ?????, schema.sql, data.sql? ????? ?????? ????.
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:log4jdbc:h2:file:/Users/junehee/june/june_tech/mybatis_study/src/main/resources/data/data;AUTO_SERVER=true
    username: sa
    password:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true  #hibernate ???? ?? ??? ???? data.sql? ??? ?? ????.
#  ???? ???? ??? ???? ???.
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  config-location: "classpath:mybatis/mybatis-config.xml"
  type-aliases-package: "com.example.mybatis_study.**.dao"
  mapper-locations: "classpath:mapper/**/*.xml"

