spring:
  sql:
    init:
      mode: always   # v2.5 ?? ?? sql.init.mode? ????? ?????, schema.sql, data.sql? ????? ?????? ????.
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/junehee/june/june_tech/mybatis_study/src/main/resources/data/data;AUTO_SERVER=true
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true  #hibernate ???? ?? ??? ???? data.sql? ??? ?? ????.
#  ???? ???? ??? ???? ???.
mybatis:
  mapper-locations: "classpath:mapper/**/*-mapper.xml"
  config-location: "classpath:mybatis/mybatis-config.xml"
