# 모든 센터 정보
http://localhost:8080/api/centers/all
Content-Type: application/json
Accept: application/json

###
## 해당 센터에 속한 모든 코치정보
http://localhost:8080/api/centers/1/coches
Content-Type: application/json
Accept: application/json