create table Member
(
    memberId bigint generated by default as identity,
    userName varchar(255),
    teamId   bigint,
    primary key (memberId)
);

create table Team
(
    teamId bigint generated by default as identity,
    name   varchar(255),
    primary key (teamId)
);

alter table Member add constraint FKnd42gy6hy2mg90pccmmdbus3p foreign key (teamId) references Team;
